export default {
  fromServer: true,
  currentView: "groups",
  syncing: false,
  lastSync: 1686588725494,
  barOpen: false,
  history: [],
  pageTitle: "Sábado, 10 de junho de 2023",
  lastCategory: "development",
  categories: [
    { name: "General", color: "#e51f75" },
    { color: "#16a085", name: "Personal" },
    { color: "#2980b9", name: "Development" },
    { color: "#0d1d45", name: "Daily" },
    { name: "Suporte", color: "#f934c4" },
    { name: "Administrativo", color: "#0aa1ff" },
    { color: "#dde010", name: "Chore" },
    { color: "#76eaa2", name: "Review" },
  ],
  groups: [
    {
      description:
        "Rotina de tarefas do início da manhã para que o dia seja massa!",
      tasks: {
        finished: [],
        active: [
          {
            recurring: true,
            title: "😴 Marcar hora em que acordou (06:30)",
            counter: 3,
            category: "personal",
            jumped: false,
            id: "lqwiSasF8Y3AyTMeG6gO",
            description: "",
            done: true,
          },
          {
            jumped: false,
            counter: 3,
            description: "",
            title: "💊 Tomar remédios",
            id: "01MhFFY7Cj4lHD035d0Q",
            recurring: true,
            category: "personal",
            done: true,
          },
          {
            done: true,
            jumped: false,
            title: "💧 Beber uma garrafa de água",
            category: "personal",
            description: "",
            counter: 3,
            id: "a38RLJ30Q4fnQi4PEv5w",
            recurring: true,
            canceled: false,
          },
          {
            title: "😃 Controle de humor da manhã - 🥱",
            done: true,
            description: "",
            recurring: true,
            counter: 3,
            category: "personal",
            id: "Kg6xn7AOdEo28WYrC1O1",
            jumped: false,
            canceled: false,
          },
          {
            done: false,
            counter: 4,
            id: "aM0D1007h51AQ6poGAqg",
            canceled: false,
            category: "personal",
            title: "🙆🏻 Fazer 5 minutos de alongamento",
            jumped: false,
            recurring: true,
            description: "",
          },
        ],
        backlog: [
          {
            counter: 3,
            id: "Qo5EjAW41s6I6jSUqAcN",
            jumped: false,
            done: false,
            description: "",
            recurring: true,
            category: "personal",
            title: "🏡 Geralzinha na casinha",
          },
          {
            id: "vaXp0txxhyiFQHM3owk6",
            title: "🌤️ Passeio da manhã",
            category: "personal",
            recurring: true,
            jumped: false,
            done: true,
            description: "",
            counter: 4,
            canceled: false,
          },
          {
            id: "J8EUWnywo836Ha2T5BNX",
            done: false,
            title: "🏁 Planejamento do dia",
            description:
              "O planejamento do dia consiste em **definir o que é o 🐸 do dia** e colocá-lo no bloco inicial, bem como separar as demais tarefas entre os blocos principais de trabalho.",
            canceled: false,
            jumped: false,
            recurring: true,
            category: "general",
            counter: 51,
          },
          {
            description: "",
            jumped: false,
            title: "👨🏻‍💻 Bloco de 1h30 de trabalho focado",
            recurring: true,
            category: "general",
            done: false,
            canceled: false,
            counter: 2,
            id: "8D4AQUH22WJx3hteMCxl",
          },
          {
            counter: 5,
            title: "🍴 Lavar as louças",
            category: "personal",
            description: "",
            id: "Hdu8b4s5tLcv36C7BK0y",
            canceled: false,
            recurring: true,
            jumped: false,
            done: false,
          },
          {
            title: "🏋️‍♀️ 30 minutos de exercícios",
            id: "2u2rX83m0Kueo7iP6qi2",
            done: false,
            recurring: true,
            canceled: false,
            counter: 3,
            category: "personal",
            description: "",
            jumped: false,
          },
          {
            counter: 3,
            title: "🛀 Tomar banho",
            description: "",
            done: false,
            id: "F8tc0743RybV1O71ubjt",
            jumped: false,
            category: "personal",
            recurring: true,
          },
          {
            category: "general",
            counter: 2,
            jumped: false,
            id: "G4Aim7enW7MOq85NPhUs",
            canceled: false,
            title: "🔁 Bloco de revisão",
            done: false,
            recurring: true,
            description: "",
          },
        ],
      },
      id: "050GV2UpUMeHX8jb3Xs3",
      ignore: false,
      name: "☀️ Acorda, menino!",
    },
    {
      id: "5Knc6IcNmInlfMN8FskC",
      ignore: false,
      name: "🎯 Bloco 1",
      description:
        "Primeiro bloco focado do dia, com 1h30 de duração. Idealmente, focado em uma única tarefa ou tarefas atreladas ao mesmo objetivo.",
      tasks: {
        backlog: [
          {
            recurring: false,
            id: "HU5x5qpD3jUK0lB1vL1F",
            done: false,
            category: "development",
            title:
              "Adicionar opção que me permita escrever hooks utilizando código, para poder conectar o Daily com o N8N, por exemplo",
            counter: 0,
            jumped: false,
            description:
              "Com isso, seria possível, por exemplo, salvar as tarefas do dia como um json em um repositório do github automáticamente, sem o medo de perder nada.",
          },
          {
            done: false,
            recurring: false,
            title: "Adicionar campos de controle de humor",
            counter: 0,
            jumped: false,
            id: "FU37tN7Ihr3YXcO5p6uJ",
            category: "development",
            description: "",
          },
          {
            recurring: false,
            title:
              'Adicionar suporte à grupos de "trabalho", que tem suas tarefas ativas limitadas',
            description: "",
            counter: 0,
            category: "development",
            jumped: false,
            done: false,
            id: "bL7YBqvTm7pKrfMn6S3J",
          },
          {
            jumped: false,
            done: false,
            id: "484Gh8lQaAdydl25mrH2",
            recurring: false,
            category: "development",
            counter: 0,
            title: "Marcar tarefa como parte do goal diário",
            description: "",
          },
          {
            recurring: false,
            description: "",
            title: "Goal review",
            category: "development",
            jumped: false,
            id: "fD7VH0il5Y4S0Hnwk7qK",
            done: false,
            counter: 0,
          },
          {
            recurring: false,
            counter: 0,
            jumped: false,
            category: "development",
            id: "d38s53VPRQ4EgH8tiFWQ",
            title:
              "Adicionar uma sintaxe para mudar o tamanho do bloco no Daily",
            description: "",
            done: false,
          },
          {
            category: "development",
            counter: 0,
            id: "Je5RfaM82Pjnv7xgV2o4",
            title:
              "Adicionar uma opção de quebrar uma tarefa em actionable steps",
            done: false,
            description: "",
            jumped: false,
            recurring: false,
          },
          {
            jumped: false,
            description: "",
            title: "Marcar tarefa como hábito",
            recurring: false,
            category: "development",
            counter: 0,
            done: false,
            id: "416bSJ5o725nnTb68AJ1",
          },
          {
            category: "development",
            recurring: false,
            id: "IJAA1iAal8d58TCkDVFw",
            done: false,
            title: "Adicionar grupo obrigatório para um horário",
            jumped: false,
            counter: 0,
            description:
              'Se um grupo é marcado como obrigatório para um horário, depois do horário marcado, ele vira o grupo "foco" e só mostra o resto depois que todas as tarefas dele estão concluídas.',
          },
          {
            title:
              'Adicionar um "modo foco" nos grupos, que esconda o resto e expanda o grupo atual para o meio da tela',
            jumped: false,
            category: "development",
            counter: 0,
            id: "XBN0k75k57CfuM8Li1E8",
            done: false,
            description: "",
            recurring: false,
          },
          {
            done: false,
            id: "L2Q4mt50Wl5YqgC4rd3p",
            recurring: false,
            description: "",
            counter: 1,
            title:
              "Adicionar funcionalidade ao Daily que o permita ter um action button para o campo de URL e que esse campo de URL suporte templating com dados baseados nos valores da tarefa",
            category: "development",
            jumped: false,
          },
          {
            category: "development",
            recurring: false,
            counter: 0,
            id: "i0A6OAnD7861C06dW7cl",
            title:
              "Adicionar suporte para uma nota que será mostrada no dia seguinte!",
            done: false,
            description: "",
            jumped: false,
          },
          {
            counter: 0,
            description: "",
            jumped: false,
            category: "development",
            recurring: false,
            title:
              "Opção de trocar para a próxima tarefa com tab, e voltar para a anterior com shift + tab",
            id: "815U1y7XyoY6EnVsB7Co",
            done: false,
          },
          {
            description: "",
            counter: 0,
            jumped: false,
            title: "Mudar a biblioteca de drag and drop utilizada no Daily",
            done: false,
            id: "60Hih72eF16ePNQrPdss",
            recurring: false,
            category: "development",
          },
          {
            id: "v5DKQS45v0BD8S5wym6H",
            title: "Adicionar a gaveta da semana",
            counter: 0,
            recurring: false,
            jumped: false,
            description:
              "A gaveta da semana é uma linha de blocos que mostra os próximos dias 7 dias. As tarefas dessa gaveta são jogadas na Inbox quando o dia começa.",
            done: false,
            category: "development",
          },
          {
            counter: 0,
            category: "development",
            recurring: false,
            id: "oJt6TpQ2Pj4gyX1q0qDE",
            jumped: false,
            title: "Organizar melhor a estrutura de arquivos do Blocks WPU-966",
            done: false,
            url: "https://linear.app/nextpress/issue/WPU-966",
            description: "",
            integration: "linear",
          },
          {
            counter: 4,
            jumped: false,
            done: false,
            title: "Plano de metas para o lançamento da funcionalidade",
            description: "",
            recurring: false,
            id: "28cv2sdcR528D2N07a6n",
            category: "development",
          },
          {
            category: "development",
            title: "Dar um tapa no código de exportação",
            counter: 1,
            recurring: false,
            id: "07v6itKK631GeSmrI05G",
            done: false,
            jumped: false,
            description: "",
          },
          {
            counter: 0,
            id: "5XaxuJ7007HlvFjioRU0",
            description: "",
            jumped: false,
            title: "Sisteminha simples de notificações",
            recurring: false,
            category: "development",
            done: false,
          },
        ],
        active: [
          {
            counter: 2,
            integrationAccount: null,
            done: false,
            url: "https://linear.app/nextpress/issue/WPU-938/app-builder",
            category: "general",
            recurring: true,
            jumped: false,
            integration: "linear",
            description:
              'Essa tarefa centraliza elementos que precisamos implementar para tirar do papel as funcionalidades de app building que queremos adicionar no Ultimo.\n\nVia de regra, a versão mais atualizada dessas tarefas está localizada no arquivo `.todos` do monorepo, mas de tempos em tempos, vou mover esses elementos para cá também.\n\nVou dividir em blocos bonitinhos para cada objetivo, e tentar dar uma data para cada um desses blocos.\n\n### Demo para o Time\n\n* [X] Formulário de Login\n  * [X] Conectar o formulário dummy que temos ao workflow de login\n  * [X] Implementar a action de login\n  * [X] Implementar o result de redirect\n  * [X] Implementar o bloco de código PHP\n* [ ] Editor de Formulários\n  * [ ] CPT de Formulários\n  * [ ] Blocos-base de Formulário\n    * [ ] Form\n      * [ ] Form Step\n        * [ ] Field Group\n        * [ ] Field Label\n        * [ ] Field Input\n        * [ ] Field Message\n      * [ ] Submit Button\n* [ ] Builder UI\n  * [ ] Context Block: Esse bloco é o responsável por mudar o contexto passado aos blocos-filhos, com base em alguns parâmetros recebidos. Ele é útil porque nos permite também oferecer a possibilidade de criar "lazy-blocks", que só são carregados via ajax depois do loading inicial, o que torna o shell do App bastante cacheável.\n  * [ ] Query Blocks: Variations do bloco de query do WordPress que vamos usar para implementar loops de elementos que não necessariamente estão relacionados com custom post types, mas sim com custom models do Ultimo ou da rede.\n    * [ ] Sites: Para o demo, só preciso do Site, que vai servir de proxy para as networks do usuário\n    * [ ] Custom Data Type: Também será necessário um data type chamado License, que será relacionada a networks específicos, e também precisará ser exibido.\n    * [ ] Depois\n      * [ ] Memberships\n      * [ ] Payments\n      * [ ] Notifications\n* [ ] Secrets\n  * [ ] Opção de salvar um secret de maneira encryptada\n  * [ ] UI para criação de secrets\n* [ ] Sistema de Notificações\n  * [ ] Criar notificação\n  * [ ] Exibir notificações\n* [ ] Inclusão do ChatGPT: Como temos aquele serviço que gera um bot usando a documentação do Ultimo e do Laravel, além da do WordPress, seria interessante ter um personal assistant para desenvolvimento utilizando o Ultimo. Ele pode gerar snippets que podem ser incluidos diretamente no bloco de execução do PHP dos nossos Workflows.',
            title: "App Builder",
            id: "6ff7d2e9-9ec4-4548-bf3c-dee8df9ab5f6",
          },
          {
            counter: 0,
            title: "Perguntar sobre o Goal do dia!",
            description: "",
            id: "M1cj3tbw77Y4Er8AtBR2",
            category: "development",
            done: false,
            recurring: false,
            jumped: false,
          },
          {
            jumped: false,
            done: false,
            category: "development",
            counter: 0,
            recurring: false,
            description: "",
            title:
              "Adicionar campos de controle da hora em que acordou e da hora em que dormiu",
            id: "03IhAdUidobKdQkqV28E",
          },
          {
            category: "development",
            done: false,
            counter: 0,
            jumped: false,
            title: "Opção de esconder um grupo",
            recurring: false,
            id: "n3nCHylm5smalyLtOdL6",
            description: "",
          },
          {
            category: "development",
            done: false,
            recurring: false,
            title:
              "Adicionar toggle nas tasks que diz se elas devem contar para o total ou não",
            id: "XfROH2Ll7T67wSS4mpeO",
            counter: 0,
            description: "",
            jumped: false,
          },
        ],
        finished: [],
      },
    },
    {
      ignore: false,
      description:
        "Sociedade pró-melhoramento do bairro de eu mesmo. Grupinho para tarefas destinadas à melhora dos sistemas que me fazem funcionar melhor e mais feliz.",
      id: "SkhAVHoFDJ6u3fItA17Q",
      tasks: {
        active: [
          {
            recurring: false,
            canceled: true,
            id: "CR4Pc7lEm7j2OiPF87ur",
            counter: 0,
            jumped: false,
            title: "Integração com o Things na Inbox",
            description: "",
            done: false,
            category: "development",
          },
        ],
        backlog: [],
        finished: [],
      },
      name: "⚒️ SPM do Arindo",
    },
    {
      tasks: {
        backlog: [
          {
            integration: "linear",
            title: "Responder a discussão que eu mesmo propus na Comunidade",
            counter: 1,
            recurring: false,
            done: false,
            url: "https://linear.app/nextpress/issue/DIR-1829/responder-a-discussao-que-eu-mesmo-propus-na-comunidade",
            category: "chore",
            integrationAccount: null,
            description: null,
            canceled: false,
            jumped: false,
            id: "8d72bd0e-d164-42fa-82ee-6eca82ece52d",
          },
          {
            description:
              "Temos que fazer uma análise de custo benefício para ver se valeria a pena, realmente, já que poderia dar bastante trabalho.",
            title: "Considerar mover o Delta para o AWS",
            counter: 2,
            integrationAccount: null,
            integration: "linear",
            id: "f941bdb8-6810-4c7f-802a-910b5ab86a46",
            done: false,
            url: "https://linear.app/nextpress/issue/DIR-1828/considerar-mover-o-delta-para-o-aws",
            recurring: false,
            jumped: false,
            category: "chore",
          },
          {
            title: "Geral na Comunidade",
            done: false,
            counter: 5,
            recurring: true,
            description: "",
            id: "oG7XIsu56LtBxH0Q673i",
            category: "chore",
            jumped: false,
            canceled: false,
          },
          {
            counter: 0,
            category: "chore",
            jumped: false,
            description: "",
            title:
              "Listar tudo que precisa ser migrado para o AWS para que o processo possa ser encerrado e os droplets do Digital Ocean sejam destruídos",
            recurring: false,
            done: false,
            id: "lC21s8voR6Ao7vfFXBdi",
          },
        ],
        finished: [],
        active: [
          {
            recurring: true,
            done: false,
            canceled: false,
            jumped: false,
            title: "Repassar tickets no Chatwoot",
            id: "01Mm8GMGB75t1F4Do86p",
            counter: 12,
            category: "suporte",
            description: "",
          },
        ],
      },
      id: "7eg8RkHv12465N15hojX",
      ignore: false,
      name: "🐸 Eat the Frog",
      description:
        "Sabemos que dói, mas temos que sempre começar com o pior, para que o dia possa melhorar dai pra frente.",
    },
    {
      description:
        "Primeiro bloco de 30 minutos, onde tarefas consideradas urgentes vão ser realizadas primeiro. Entre 10:30-11:00",
      ignore: true,
      tasks: { finished: [], active: [], backlog: [] },
      name: "✨ Urgentes",
      id: "x131rJjraIhvTvf4shpL",
    },
    {
      name: "🏃 Chores",
      id: "15RRj1kyPiyUa46T6Xnd",
      ignore: true,
      tasks: {
        backlog: [
          {
            description: "",
            done: false,
            title: "Criar demos para todos os produtos no InstaWP",
            jumped: false,
            id: "4ji0Q12ot1WOw73Xvc54",
            category: "administrativo",
            recurring: false,
            counter: 0,
          },
          {
            id: "X2363uFuU6BLw61i4PW1",
            counter: 0,
            integration: "linear",
            category: "chore",
            jumped: false,
            title:
              "Listar todos os domínios que tenho - e talvez migrar eles para algum lugar único DIR-1942",
            description: "",
            recurring: false,
            done: false,
            url: "https://linear.app/nextpress/issue/DIR-1942",
          },
          {
            description: "",
            jumped: false,
            done: false,
            category: "chore",
            title: "Adicionar o arindoduque.com ao InfiniteWP",
            id: "CwA7DVyst3lrq44n5fr3",
            counter: 0,
            recurring: false,
          },
          {
            title:
              "Adicionar vendas dos demais plugins à planilha de vendas também",
            description: null,
            jumped: false,
            integrationAccount: null,
            counter: 0,
            url: "https://linear.app/nextpress/issue/DIR-1881/adicionar-vendas-dos-demais-plugins-a-planilha-de-vendas-tambem",
            id: "4673c079-bb0d-4a1d-a174-a13e93b7428a",
            done: false,
            integration: "linear",
            category: "chore",
          },
          {
            done: false,
            category: "administrativo",
            description: "",
            id: "X742ma4Y14m43sJ5rXwf",
            recurring: false,
            title:
              "Pensar em como posso delegar os tickets de suporte para o Gustavo",
            jumped: false,
            counter: 0,
          },
          {
            integration: "linear",
            counter: 0,
            category: "development",
            id: "568a9b03-2f9b-4718-aca1-6c453d77e3eb",
            description:
              "Link do Ticket no Chatwoot: [https://support.delta.nextpress.co/app/accounts/1/conversations/289](https://support.delta.nextpress.co/app/accounts/1/conversations/289)",
            title: "Demo para a Nicole dos Workflows (remarcar)",
            integrationAccount: null,
            jumped: false,
            done: false,
            url: "https://linear.app/nextpress/issue/DIR-1885/demo-para-a-nicole-dos-workflows",
          },
          {
            integration: "linear",
            title:
              "Definir qual é o objetivo de grana antes de largar tudo e o limite de tempo",
            id: "a66ce834-d8ea-4461-b7d1-b1228f9a2696",
            url: "https://linear.app/nextpress/issue/MEU-108/definir-qual-e-o-objetivo-de-grana-antes-de-largar-tudo-e-o-limite-de",
            integrationAccount: null,
            jumped: false,
            description:
              "Ideia inicial: até o dia 31/12 do ano em que eu tenha 30 anos.",
            done: false,
            counter: 0,
            category: "development",
          },
          {
            jumped: false,
            description: "",
            integration: "linear",
            counter: 0,
            done: false,
            title: "Viral do ChatGPT",
            id: "54caa2e5-1793-42a1-a34e-f963ff65b89c",
            integrationAccount: null,
            url: "https://linear.app/nextpress/issue/MEU-48/viral-do-chatgpt",
            category: "development",
          },
        ],
        finished: [],
        active: [
          {
            jumped: false,
            category: "administrativo",
            id: "6FJnn5XhdXmYL2egBmI2",
            recurring: true,
            counter: 0,
            title: "Listar o plano de ação de para o time",
            done: false,
            description: "",
          },
        ],
      },
      description:
        "Bloco de 1h30~2h00 para realizar algumas tarefas manuais. Entre 13:30-14:30.",
    },
    {
      tasks: { finished: [], backlog: [], active: [] },
      description:
        "Tarefas para a manutenção de um lar agradável. Entre 14:30 e a hora do almoço.",
      id: "AoQwrgziEAQDIHsB2BzaQ",
      name: "🏡 Tarefas domésticas",
      ignore: true,
    },
    {
      ignore: true,
      id: "CjJIeHvnO3f80AG113E2",
      name: "🏃 Exercícios",
      tasks: {
        finished: [],
        backlog: [
          {
            counter: 0,
            recurring: false,
            done: false,
            title: "Implementar a rotina matinal do Andrew Huberman",
            description: "",
            jumped: false,
            id: "6NKRFBmC34Ofx6lUS2sF",
            category: "personal",
          },
        ],
        active: [],
      },
      description: "Lista de exercícios físicos.",
    },
    {
      description: "Tarefas relacionadas com o treinamento do Vily.",
      tasks: {
        finished: [],
        backlog: [],
        active: [
          {
            recurring: true,
            description: "",
            canceled: false,
            title: "🦴 Treino de ansiedade de comida",
            done: false,
            counter: 1,
            category: "personal",
            id: "qieyJB2S621tLQYMeR11",
            jumped: false,
          },
          {
            done: false,
            counter: 1,
            title: "🌙 Passeio da noite",
            id: "0p2Evkf7rEwL1Xi72e13",
            description: "",
            recurring: true,
            jumped: false,
            category: "personal",
          },
        ],
      },
      id: "h64cBB68pQa6x4jX2uh7",
      name: "Vily, the 🐕",
      ignore: true,
    },
    {
      id: "Ga1HCcwRyxs3oEI6l04B",
      description: "Rotinas de tarefas para recomeçar depois do almoço.",
      ignore: true,
      tasks: {
        finished: [],
        active: [
          {
            done: false,
            id: "4E48dGU708KMBT44UE7W",
            title: "Beber uma garrafa de água",
            description: "",
            recurring: true,
            counter: 2,
            jumped: false,
            category: "personal",
          },
          {
            recurring: true,
            counter: 1,
            jumped: false,
            id: "ARMrLdxr3DGx1C6y2v5B",
            category: "personal",
            description: "",
            done: false,
            title: "Controle de humor da tarde (😴)",
          },
          {
            description: "",
            done: false,
            recurring: true,
            canceled: false,
            jumped: false,
            category: "personal",
            title:
              "Escrever uma nota sobre como foi a manhã e o que pode melhorar para a tarde",
            id: "132Ycj7bx4VsdgmDJI8I",
            counter: 1,
          },
        ],
        backlog: [],
      },
      name: "☕️ A tarde é sua",
    },
    {
      name: "🌙 Deu por hoje",
      ignore: true,
      description:
        "Rotina final do dia, com foco em review, gratidão e o dia de amanhã.",
      id: "0UhjRwEGIbOX04ovno65",
      tasks: {
        backlog: [
          {
            counter: 0,
            title: "Controle de humor da noite",
            done: false,
            jumped: false,
            canceled: false,
            description: "",
            id: "OjBB0R8B723x1ckQ1igB",
            category: "personal",
            recurring: true,
          },
          {
            category: "personal",
            counter: 0,
            recurring: true,
            title: "Um recado para o eu de amanhã!",
            id: "1T8ijn54s4ys0IaJr8Ni",
            done: false,
            description: "",
            canceled: false,
            jumped: false,
          },
        ],
        active: [
          {
            id: "5MnV34vc167qCH1XRRPK",
            title: "Beber uma garrafa de água",
            jumped: false,
            description: "",
            done: false,
            category: "personal",
            counter: 0,
            recurring: true,
          },
          {
            category: "personal",
            description: "",
            canceled: false,
            recurring: true,
            jumped: false,
            counter: 0,
            done: false,
            id: "5AQhwVbKJ76ORehLkhPY",
            title: "Revisar os hábitos marcados no Streaks",
          },
          {
            recurring: true,
            id: "m15eW7vUyub7362KT3bW",
            category: "general",
            counter: 0,
            jumped: false,
            done: false,
            canceled: false,
            title:
              "Revisar o calendário para eventos que precisam estar no radar",
            description: "",
          },
          {
            counter: 0,
            category: "general",
            id: "1SHqD850lVW3X50y7FRG",
            description: "",
            done: false,
            title: "Revisar os blocos do session e as notas deixadas",
            canceled: false,
            recurring: true,
            jumped: false,
          },
          {
            jumped: false,
            id: "PMP1L08yA7v8vwAR21LM",
            recurring: true,
            description: "",
            title: "Marcar a hora em que parou",
            counter: 2,
            done: false,
            canceled: false,
            category: "personal",
          },
        ],
        finished: [],
      },
    },
    {
      id: "EoUwxg9gTlIHYBcQGcg",
      name: "🔁 Bloco de revisão",
      description: "Tarefas recorrentes, que rolam todo dia.",
      ignore: false,
      tasks: {
        finished: [],
        active: [
          {
            recurring: true,
            category: "chore",
            id: "02df4Bg6XL7Np833XNXE",
            jumped: false,
            title: "Review das issues no Linear",
            done: false,
            description: "",
            counter: 13,
            canceled: false,
          },
          {
            description: "",
            id: "nBt25k555TJRCK8vhWy1",
            category: "chore",
            canceled: false,
            counter: 2,
            done: false,
            title: "Review de notificações no Github",
            jumped: false,
            recurring: true,
          },
          {
            description: "",
            title: "Inbox Zero",
            recurring: true,
            canceled: false,
            category: "chore",
            done: false,
            id: "0wellkbS5b0H0HOA3mp4",
            jumped: false,
            counter: 33,
          },
          {
            done: false,
            category: "personal",
            recurring: true,
            title: "Revisar o WhatsApp",
            canceled: false,
            description: "",
            jumped: false,
            counter: 0,
            id: "BasEw7RTQFg4EP22FvFB",
          },
        ],
        backlog: [],
      },
    },
    {
      id: "731hBji6kME8Ip4afIpV",
      name: "📥 Inbox",
      description: "Tarefas que descobri e precisam ser distribuidas",
      tasks: {
        active: [],
        backlog: [
          {
            done: false,
            description: "",
            jumped: false,
            id: "2eieQi45AQ0n4AKQ71AU",
            counter: 0,
            recurring: false,
            title: "Ver conta e integração com o i20",
            category: "development",
          },
        ],
        finished: [],
      },
      ignore: true,
    },
    {
      id: "Kgy2rN6o4N3Ua2p03p46",
      tasks: {
        backlog: [
          {
            recurring: true,
            title: "Pedir refund Neil Patel",
            description: "",
            jumped: false,
            category: "general",
            counter: 0,
            done: false,
            canceled: true,
            id: "tu3n1GlQ8xTX6PWuJ1YO",
          },
        ],
        active: [
          {
            done: true,
            title:
              "Colocar o Dropbox para rodar de madrugada e criar lembretes para fazer backups da time machine recorrentemente",
            counter: 0,
            recurring: false,
            jumped: false,
            canceled: false,
            id: "658h01MYpkyyf5kCl53D",
            description: "",
            category: "chore",
          },
        ],
        finished: [],
      },
      description: "Tarefinhas que podem ser realizadas em 5min ou menos.",
      ignore: true,
      name: "⚽️ Bate-bola, jogo rápido",
    },
    {
      id: "18rEBJ7pHRvlrrJ6NcnL",
      tasks: { active: [], backlog: [], finished: [] },
      ignore: true,
      description: "Tarefinhas que precisam ser desenvolvidas hoje.",
      name: "🥾 Encaminhamentos",
    },
    {
      ignore: true,
      tasks: {
        finished: [],
        backlog: [
          {
            title:
              "Fix do Freemius SDK não funciona se outro plugin adiciona o SDK também WPU-662",
            done: false,
            url: "https://linear.app/nextpress/issue/WPU-662",
            counter: 0,
            id: "R11E6pRh8nP26uB0M8Tu",
            integration: "linear",
            description: "",
            jumped: false,
            category: "development",
            recurring: false,
          },
        ],
        active: [],
      },
      id: "681eXEXR7e4k4D3IPauH",
      name: "👨🏻‍💻 Desenvolvimento",
      description: "Tarefas relacionadas à programação.",
    },
    {
      ignore: true,
      tasks: {
        finished: [],
        backlog: [
          {
            title:
              "Adicionar fotos dos eventos da Comunidade de WordPress de Juiz de Fora (talvez fazer o back-dating?)",
            description: null,
            integrationAccount: null,
            done: false,
            jumped: false,
            integration: "linear",
            url: "https://linear.app/nextpress/issue/MEU-59/adicionar-fotos-dos-eventos-da-comunidade-de-wordpress-de-juiz-de-fora",
            category: "development",
            counter: 0,
            id: "d80aa0a8-a051-4c85-aa42-9519aa2ae671",
          },
          {
            url: "https://linear.app/nextpress/issue/MEU-61/escrever-cover-letters-para-cada-vaga",
            counter: 1,
            done: false,
            description: null,
            category: "development",
            id: "b1047782-f633-47a6-b06d-715662a7440a",
            integrationAccount: null,
            integration: "linear",
            jumped: false,
            title: "Escrever cover letters para cada vaga",
          },
          {
            counter: 0,
            description: null,
            done: false,
            integration: "linear",
            url: "https://linear.app/nextpress/issue/MEU-53/atualizar-meu-site-pessoal-para-me-certificar-de-que-ele-tem-tudo-que",
            category: "development",
            id: "2c73d3f7-c64c-4b5e-b3bf-5364c2686448",
            integrationAccount: null,
            jumped: false,
            title:
              "Atualizar meu site pessoal para me certificar de que ele tem tudo que precisa ter",
          },
          {
            category: "development",
            integration: "linear",
            id: "2080cc93-571c-4e61-9b38-00edc7a33f2a",
            url: "https://linear.app/nextpress/issue/MEU-55/buscar-referencias-de-coisas-legais-para-incluir-baseado-no-site-do",
            description: null,
            counter: 1,
            title:
              "Buscar referências de coisas legais para incluir, baseado no site do Felipe",
            integrationAccount: null,
            jumped: false,
            done: false,
          },
          {
            integration: "linear",
            done: false,
            jumped: false,
            id: "91eb9f06-ceab-400c-89a7-57cc4e50cf15",
            integrationAccount: null,
            url: "https://linear.app/nextpress/issue/NEX-421/post-sobre-experimentos-com-o-chatgpt-dando-a-entender-que-algo-como-o",
            title:
              "Post sobre experimentos com o ChatGPT, dando a entender que algo como o Viral descrito aqui está por vir",
            description: null,
            counter: 0,
            category: "development",
          },
          {
            category: "development",
            done: false,
            counter: 0,
            title:
              "Copiar os formulários de aplicação para que possa respondê-los aqui no Linear",
            jumped: false,
            integrationAccount: null,
            id: "78f4191c-f75f-4229-8262-df74188f3857",
            integration: "linear",
            url: "https://linear.app/nextpress/issue/MEU-60/copiar-os-formularios-de-aplicacao-para-que-possa-responde-los-aqui-no",
            description: null,
          },
        ],
        active: [],
      },
      name: "🏢 Busca de emprego",
      description: "Tarefas relacionadas à busca de empregos.",
      id: "0YWQFiRXgmcXf54rb7XI",
    },
    {
      tasks: {
        active: [
          {
            counter: 0,
            url: "https://linear.app/nextpress/issue/NEX-432/pesquisa-de-que-keywords-devemos-mirar",
            title: "Pesquisa de que keywords devemos mirar",
            integration: "linear",
            done: false,
            integrationAccount: null,
            id: "0c31b1e9-ff58-4c3b-8c99-d84671679ba3",
            category: "development",
            description: null,
            jumped: false,
          },
          {
            done: false,
            jumped: false,
            description:
              "* [ ] [SEO Crash Course | Beginners and Experts Welcome](https://www.keysearch.co/tutorials/seo-crash-course)",
            integration: "linear",
            url: "https://linear.app/nextpress/issue/NEX-459/crash-course-de-seo-para-beginners",
            title: "Crash course de SEO para beginners",
            id: "f07baed5-4192-4f10-8c63-0fe263c290ab",
            category: "development",
            integrationAccount: null,
            counter: 0,
          },
          {
            url: "https://linear.app/nextpress/issue/NEX-428/curso-de-seo-para-developers",
            counter: 0,
            category: "development",
            jumped: false,
            id: "a391da51-279a-4517-b464-22a5139e188b",
            description: null,
            integration: "linear",
            title: "Curso de SEO para developers",
            integrationAccount: null,
            done: false,
          },
          {
            integrationAccount: null,
            id: "1545c5ee-e444-4fcb-8902-256e2afa31f4",
            title: "Email sequencies",
            counter: 0,
            jumped: false,
            category: "development",
            done: false,
            integration: "linear",
            url: "https://linear.app/nextpress/issue/NEX-423/email-sequencies",
            description: null,
          },
          {
            done: false,
            title: "Pesquisar como fazer uma boa segmentação da minha lista",
            id: "4d206d75-c9c4-4892-ab3f-c82a957a5dd9",
            url: "https://linear.app/nextpress/issue/NEX-427/pesquisar-como-fazer-uma-boa-segmentacao-da-minha-lista",
            counter: 1,
            integration: "linear",
            category: "development",
            jumped: false,
            description: null,
            integrationAccount: null,
          },
        ],
        backlog: [
          {
            counter: 0,
            done: false,
            integration: "linear",
            title:
              "Calendário de publicações de postagens, com base nas keywords",
            jumped: false,
            description: null,
            id: "0a21afed-21a0-451b-8f21-aed42c5ef923",
            category: "development",
            integrationAccount: null,
            url: "https://linear.app/nextpress/issue/NEX-436/calendario-de-publicacoes-de-postagens-com-base-nas-keywords",
          },
          {
            counter: 0,
            done: false,
            title:
              "Plano para acompanhar as keywords escolhidas ao longo do tempo",
            url: "https://linear.app/nextpress/issue/NEX-435/plano-para-acompanhar-as-keywords-escolhidas-ao-longo-do-tempo",
            jumped: false,
            integration: "linear",
            integrationAccount: null,
            category: "development",
            id: "0631bfb9-6362-4f1c-bbdf-17956ec61743",
            description: null,
          },
          {
            url: "https://linear.app/nextpress/issue/NEX-434/adicionar-meta-data-para-seo-em-todas-as-postagens-existentes",
            integration: "linear",
            description: null,
            id: "b0fcb567-8b04-467f-ae24-10a0550005c5",
            counter: 0,
            jumped: false,
            category: "development",
            title:
              "Adicionar meta data para SEO em todas as postagens existentes",
            done: false,
            integrationAccount: null,
          },
          {
            description: null,
            counter: 0,
            integration: "linear",
            jumped: false,
            category: "development",
            title: "Pessoas que entram no demo",
            url: "https://linear.app/nextpress/issue/NEX-424/pessoas-que-entram-no-demo",
            done: false,
            integrationAccount: null,
            id: "9e1543a4-e2fc-4b87-a8c5-eca7a29191cb",
          },
          {
            title: "Revisão das perguntas da Survey de 2023",
            integrationAccount: null,
            category: "development",
            jumped: false,
            id: "9723bd14-ecf8-4b25-80dd-8c5f5dcc2916",
            url: "https://linear.app/nextpress/issue/WPU-971/revisao-das-perguntas-da-survey-de-2023",
            description: null,
            counter: 0,
            integration: "linear",
            done: false,
          },
          {
            jumped: false,
            id: "d99e015a-8181-4934-87ab-eb5d8643f604",
            description: null,
            category: "general",
            integrationAccount: null,
            url: "https://linear.app/nextpress/issue/NEX-441/explicar-o-que-e-uma-network-idealmente-com-conteudo-em-video",
            title:
              "Explicar o que é uma Network, idealmente com conteúdo em vídeo",
            done: false,
            integration: "linear",
            counter: 0,
          },
          {
            id: "h3p1y13PdlV2cvOVK8Nh",
            description: "",
            recurring: false,
            category: "development",
            counter: 0,
            done: false,
            jumped: false,
            title: "https://gridpane.com/kb/using-wp-ultimo-with-gridpane/",
          },
          {
            description: "",
            category: "development",
            title: "https://www.trustpilot.com/review/wpultimo.com",
            counter: 0,
            recurring: false,
            jumped: false,
            id: "x0PuswlJxRxrYnfq1IVI",
            done: false,
          },
        ],
        finished: [],
      },
      id: "lm2oB5486wP00x845jA4",
      description: "Tarefas de marketing para o produto.",
      ignore: true,
      name: "📢 Marketing e SEO",
    },
    {
      tasks: {
        backlog: [],
        active: [
          {
            jumped: false,
            description: "",
            counter: 0,
            title: "Atualizar o Roadmap",
            id: "Usl7IdHUS82nA52385Ss",
            recurring: false,
            done: false,
            category: "general",
          },
          {
            description: null,
            counter: 0,
            jumped: false,
            id: "c5353d6e-77aa-4c69-b93d-49c529b33cf5",
            title:
              "Ajustes nas postagens existentes, para que o ranking seja melhor para as keywords que selecionamos",
            integration: "linear",
            done: false,
            url: "https://linear.app/nextpress/issue/NEX-433/ajustes-nas-postagens-existentes-para-que-o-ranking-seja-melhor-para",
            integrationAccount: null,
            category: "general",
          },
          {
            title: "Substituir o site do NextPress por uma tela de espera",
            description: null,
            integrationAccount: null,
            category: "general",
            jumped: false,
            url: "https://linear.app/nextpress/issue/NEX-444/substituir-o-site-do-nextpress-por-uma-tela-de-espera",
            counter: 0,
            id: "bb141f0a-8409-491a-a1b8-372466b2da83",
            integration: "linear",
            done: false,
          },
          {
            jumped: false,
            id: "7cac2604-22f3-4dbb-b38c-3ec357dfc33a",
            done: false,
            counter: 0,
            integration: "linear",
            url: "https://linear.app/nextpress/issue/NEX-438/mover-os-posts-do-antigo-roadmap",
            category: "general",
            integrationAccount: null,
            description: null,
            title: "Mover os posts do antigo roadmap",
          },
        ],
        finished: [],
      },
      description: "Tarefas para descrever e passar para terceiros.",
      name: "👊🏼 Para delegar",
      ignore: true,
      id: "6O4H15Yiji4SLNg7WV5x",
    },
    {
      ignore: true,
      tasks: {
        active: [
          {
            jumped: false,
            integration: "chatwoot",
            url: "https://support.delta.nextpress.co/app/accounts/1/conversations/497",
            category: "chore",
            counter: 0,
            title: "Tickets do Tyler para revisar (WPU-926, WPU-904, CW-497)",
            done: false,
            recurring: true,
            id: "5A2SS6YPVv8tSl1PuxWh",
            description:
              "Pedir um resumo do Lucas sobre a situação sobre esses tickets.",
          },
          {
            category: "chore",
            counter: 0,
            done: false,
            title: "Merge na branch da 2.1.1 do Ultimo",
            recurring: true,
            description: "",
            jumped: false,
            id: "wd86Gu6Y3N8h1g02OnNS",
          },
          {
            url: "https://linear.app/nextpress/issue/NEX-447/criar-template-de-checklist-para-o-lancamento-de-uma-nova-versao",
            integration: "linear",
            jumped: false,
            id: "e8e675a1-5a90-4892-bd28-bbc91144a133",
            description:
              "O processo de lançamento de uma nova versão é bastante repetitivo e quase sempre envolve os mesmos passos. Com base nisso, o ideal é termos um template que possamos  utilizar sempre que uma nova versão precisar ser lançada.",
            category: "general",
            integrationAccount: null,
            recurring: true,
            done: false,
            counter: 0,
            title:
              "Criar template de checklist para o lançamento de uma nova versão",
          },
          {
            jumped: false,
            recurring: true,
            done: false,
            url: "https://linear.app/nextpress/issue/NEX-442/pagina-de-changelog-atualizar-para-a-nova-versao",
            title: "Página de Changelog - atualizar para a nova versão",
            description: null,
            integration: "linear",
            integrationAccount: null,
            category: "general",
            counter: 1,
            id: "902c12f7-1407-4e77-afda-06ce07deca3b",
          },
        ],
        backlog: [],
        finished: [],
      },
      description: "Lista para o acompanhamento das tarefas delegadas.",
      id: "2y6Y85jpN3Y0eos71bfh",
      name: "🙏 Delegadas",
    },
    {
      id: "oUOs0Lv7kYH21O4MM6du",
      tasks: { active: [], finished: [], backlog: [] },
      name: "📡 No Radar",
      description:
        "Coisas que não são para agora, mas precisam estar no radar.",
      ignore: true,
    },
    {
      name: "😄 Pessoal",
      ignore: true,
      id: "inn173UbbM4I7pB1c0Y2",
      tasks: {
        backlog: [
          {
            category: "personal",
            id: "hr4vSOIH5dqCdhCQiauv",
            description: "",
            done: false,
            counter: 1,
            jumped: false,
            title: "Organizar o Streaks com os hábitos corretos",
            recurring: false,
          },
        ],
        active: [
          {
            recurring: true,
            title: "🥁 Tocar Bateria",
            jumped: false,
            description: "",
            canceled: false,
            id: "0UO37741BGRV7U18NrWE",
            category: "personal",
            counter: 3,
            done: false,
          },
        ],
        finished: [],
      },
      description: "Lista de tarefas pessoais.",
    },
    {
      name: "🌤️ Depois de comer",
      description:
        'Tarefas mais "leves", para fazer durante a digestão. Bloco de entre 30min e 1h.',
      id: "XGQ7S747W1qb545n082A",
      ignore: false,
      tasks: {
        finished: [],
        backlog: [
          {
            description: "",
            category: "administrativo",
            counter: 0,
            id: "a1G2yij6026q5Xwo0n82",
            jumped: false,
            done: false,
            title: "Ver o lance do contrato do Trampos",
            recurring: false,
            canceled: true,
          },
        ],
        active: [
          {
            counter: 0,
            category: "chore",
            jumped: false,
            title: "⌨️ Monkeytype?",
            recurring: true,
            description: "",
            id: "RmdiGVu5xB1FGO1gpGT7",
            done: false,
          },
        ],
      },
    },
    {
      ignore: false,
      tasks: {
        active: [
          {
            description: "",
            counter: 6,
            category: "personal",
            recurring: true,
            done: false,
            canceled: false,
            id: "25il6rQEh0uI4FsC45Ih",
            title: "☀️ Passeio da tarde",
            jumped: false,
          },
        ],
        backlog: [],
        finished: [],
      },
      name: "💤 Antes de dormir",
      description: "Tarefinhas mais leves, para fechar o dia e ir dormir.",
      id: "5ei27L0lA05cXtrHP337",
    },
    {
      name: "🚀 Bloco 2",
      ignore: true,
      description:
        "Segundo bloco focado do dia, com 2:00 de duração. Idealmente, focado em uma única tarefa ou tarefas atreladas ao mesmo objetivo. Feito na tarde.",
      id: "144rJ5I7O1K8b8W13piV",
      tasks: {
        active: [
          {
            title:
              "Invoice App - Saving the contents of the inputs on the models",
            category: "development",
            done: false,
            recurring: false,
            counter: 2,
            jumped: false,
            id: "C7LC7584uXCW8DTx87bJ",
            description: "",
          },
          {
            title: "Invoice App - Register the model classes for the new types",
            jumped: false,
            done: false,
            counter: 0,
            category: "development",
            recurring: false,
            description: "",
            id: "3dBh0las86p6e86Ry0Pe",
          },
          {
            done: false,
            title:
              "Invoice App - Adding validation to the inputs before saving, using Form Requests",
            counter: 0,
            jumped: false,
            category: "development",
            id: "0uYdT2Wp5X07IL8mX1iT",
            recurring: false,
            description: "",
          },
          {
            description: "",
            category: "development",
            jumped: false,
            counter: 5,
            recurring: true,
            title: "Invoice App - Attributes Engine",
            id: "W23oySdkiuV415MOR5ll",
            done: false,
          },
        ],
        backlog: [],
        finished: [],
      },
    },
  ],
  inbox: {
    tasks: [
      {
        recurring: true,
        title: "😴 Marcar hora em que acordou (06:30)",
        category: "personal",
        done: true,
        description: "",
        id: "lqwiSasF8Y3AyTMeG6gO",
        counter: 3,
        jumped: false,
      },
      {
        done: true,
        id: "01MhFFY7Cj4lHD035d0Q",
        title: "💊 Tomar remédios",
        category: "personal",
        jumped: false,
        description: "",
        recurring: true,
        counter: 3,
      },
    ],
    name: "📥 Inbox",
    description: "Tarefas que ainda não foram categorizadas.",
  },
  settings: {
    actionStart:
      "session:///start?intent={{taskTitle}}&duration={{duration}}&notes={{taskDescription}}&categoryName={{taskCategory}}",
    maxSkips: 3,
    lang: "pt-br",
    maxTasksPerGroup: 5,
    maxGroups: 3,
    linearApiKey: "",
    pomodoroLength: 20,
    actionComplete: "session:///break",
    actionPause: "session:///pause",
    maxRoundsPerTask: 3,
  },
  hoveredGroup: "050GV2UpUMeHX8jb3Xs3",
  hoveredTask: {
    groupId: "050GV2UpUMeHX8jb3Xs3",
    taskId: "aM0D1007h51AQ6poGAqg",
  },
  currentTask: {
    counter: 3,
    category: "personal",
    description: "",
    title: "😴 Marcar hora em que acordou (06:30)",
    id: "lqwiSasF8Y3AyTMeG6gO",
    recurring: true,
    done: true,
    jumped: false,
  },
  currentSession: null,
  expandedActiveTaskBar: false,
  sessions: null,
  hash: null,
  userId: null,
  uiState: { settings: { screenName: null, object: null, open: false } },
  capital: true,
  pushNotificationToken:
    "fsjbODO043ZvzeX4C3nbgZ:APA91bEhMGsVozg_Hi9qQVjAopAUP_G2niuEFR2omqgzy38Tk4OOVjiPFED_lWpw7p4uBF83aEuRUFr9jTEKOy9cdpnrUtfq76u13zGRYAuDtc2p3lKXuxvNcCuwDG6bebcNwQVJqVtJ",
};
